#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    exit 1
fi

if [[ "$file" =~ ".*\.json" ]]; then
  exec jq -C . "$file"
  exit 0
fi

if [[ "$file" =~ ".*\.pdf$" ]]; then
  exec command less "$file"
  exit 0
fi

exec bat --style=plain --color=always --paging=never --terminal-width=$w --wrap=auto "$file"
